
# cargo-vet config file

[imports.bytecode-alliance]
url = "https://raw.githubusercontent.com/bytecodealliance/wasmtime/main/supply-chain/audits.toml"

[imports.embark-studios]
url = "https://raw.githubusercontent.com/EmbarkStudios/rust-ecosystem/main/audits.toml"

[imports.firefox]
url = "https://hg.mozilla.org/mozilla-central/raw-file/tip/supply-chain/audits.toml"

[imports.isrg]
url = "https://raw.githubusercontent.com/divviup/libprio-rs/main/supply-chain/audits.toml"

[imports.zcash]
url = "https://raw.githubusercontent.com/zcash/rust-ecosystem/main/supply-chain/audits.toml"

[policy.fpe]
audit-as-crates-io = false

[[exemptions.aes]]
version = "0.7.5"
criteria = "safe-to-run"

[[exemptions.bitflags]]
version = "1.3.2"
criteria = "safe-to-run"

[[exemptions.block-modes]]
version = "0.8.1"
criteria = "safe-to-deploy"

[[exemptions.block-padding]]
version = "0.2.1"
criteria = "safe-to-deploy"

[[exemptions.bstr]]
version = "0.2.17"
criteria = "safe-to-run"

[[exemptions.cast]]
version = "0.3.0"
criteria = "safe-to-run"

[[exemptions.cipher]]
version = "0.3.0"
criteria = "safe-to-deploy"

[[exemptions.clap]]
version = "2.34.0"
criteria = "safe-to-run"

[[exemptions.cpufeatures]]
version = "0.2.5"
criteria = "safe-to-run"

[[exemptions.criterion]]
version = "0.3.6"
criteria = "safe-to-run"

[[exemptions.criterion-cycles-per-byte]]
version = "0.1.3"
criteria = "safe-to-run"

[[exemptions.criterion-plot]]
version = "0.4.5"
criteria = "safe-to-run"

[[exemptions.crossbeam-channel]]
version = "0.5.6"
criteria = "safe-to-run"

[[exemptions.crossbeam-deque]]
version = "0.8.2"
criteria = "safe-to-run"

[[exemptions.crossbeam-epoch]]
version = "0.9.13"
criteria = "safe-to-run"

[[exemptions.crossbeam-utils]]
version = "0.8.14"
criteria = "safe-to-run"

[[exemptions.csv]]
version = "1.1.6"
criteria = "safe-to-run"

[[exemptions.csv-core]]
version = "0.1.10"
criteria = "safe-to-run"

[[exemptions.either]]
version = "1.8.0"
criteria = "safe-to-run"

[[exemptions.generic-array]]
version = "0.14.6"
criteria = "safe-to-deploy"

[[exemptions.hermit-abi]]
version = "0.1.19"
criteria = "safe-to-run"

[[exemptions.hermit-abi]]
version = "0.2.6"
criteria = "safe-to-run"

[[exemptions.itertools]]
version = "0.10.5"
criteria = "safe-to-run"

[[exemptions.itoa]]
version = "0.4.8"
criteria = "safe-to-run"

[[exemptions.itoa]]
version = "1.0.5"
criteria = "safe-to-run"

[[exemptions.js-sys]]
version = "0.3.60"
criteria = "safe-to-run"

[[exemptions.lazy_static]]
version = "1.4.0"
criteria = "safe-to-run"

[[exemptions.libc]]
version = "0.2.139"
criteria = "safe-to-run"

[[exemptions.libm]]
version = "0.2.6"
criteria = "safe-to-deploy"

[[exemptions.memchr]]
version = "2.5.0"
criteria = "safe-to-run"

[[exemptions.memoffset]]
version = "0.7.1"
criteria = "safe-to-run"

[[exemptions.num_cpus]]
version = "1.15.0"
criteria = "safe-to-run"

[[exemptions.once_cell]]
version = "1.17.0"
criteria = "safe-to-run"

[[exemptions.oorandom]]
version = "11.1.3"
criteria = "safe-to-run"

[[exemptions.opaque-debug]]
version = "0.3.0"
criteria = "safe-to-run"

[[exemptions.plotters]]
version = "0.3.4"
criteria = "safe-to-run"

[[exemptions.plotters-backend]]
version = "0.3.4"
criteria = "safe-to-run"

[[exemptions.plotters-svg]]
version = "0.3.3"
criteria = "safe-to-run"

[[exemptions.proc-macro2]]
version = "1.0.50"
criteria = "safe-to-run"

[[exemptions.regex]]
version = "1.7.1"
criteria = "safe-to-run"

[[exemptions.regex-automata]]
version = "0.1.10"
criteria = "safe-to-run"

[[exemptions.regex-syntax]]
version = "0.6.28"
criteria = "safe-to-run"

[[exemptions.ryu]]
version = "1.0.12"
criteria = "safe-to-run"

[[exemptions.same-file]]
version = "1.0.6"
criteria = "safe-to-run"

[[exemptions.scopeguard]]
version = "1.1.0"
criteria = "safe-to-run"

[[exemptions.serde]]
version = "1.0.152"
criteria = "safe-to-run"

[[exemptions.serde_derive]]
version = "1.0.152"
criteria = "safe-to-run"

[[exemptions.serde_json]]
version = "1.0.91"
criteria = "safe-to-run"

[[exemptions.syn]]
version = "1.0.107"
criteria = "safe-to-run"

[[exemptions.textwrap]]
version = "0.11.0"
criteria = "safe-to-run"

[[exemptions.tinytemplate]]
version = "1.2.1"
criteria = "safe-to-run"

[[exemptions.typenum]]
version = "1.16.0"
criteria = "safe-to-deploy"

[[exemptions.unicode-ident]]
version = "1.0.6"
criteria = "safe-to-run"

[[exemptions.unicode-width]]
version = "0.1.10"
criteria = "safe-to-run"

[[exemptions.version_check]]
version = "0.9.4"
criteria = "safe-to-deploy"

[[exemptions.walkdir]]
version = "2.3.2"
criteria = "safe-to-run"

[[exemptions.wasm-bindgen]]
version = "0.2.83"
criteria = "safe-to-run"

[[exemptions.wasm-bindgen-backend]]
version = "0.2.83"
criteria = "safe-to-run"

[[exemptions.wasm-bindgen-macro]]
version = "0.2.83"
criteria = "safe-to-run"

[[exemptions.wasm-bindgen-macro-support]]
version = "0.2.83"
criteria = "safe-to-run"

[[exemptions.wasm-bindgen-shared]]
version = "0.2.83"
criteria = "safe-to-run"

[[exemptions.web-sys]]
version = "0.3.60"
criteria = "safe-to-run"

[[exemptions.winapi]]
version = "0.3.9"
criteria = "safe-to-run"

[[exemptions.winapi-i686-pc-windows-gnu]]
version = "0.4.0"
criteria = "safe-to-run"

[[exemptions.winapi-util]]
version = "0.1.5"
criteria = "safe-to-run"

[[exemptions.winapi-x86_64-pc-windows-gnu]]
version = "0.4.0"
criteria = "safe-to-run"

