name: Audits

on: [push, pull_request]

permissions:
  contents: read

jobs:
  cargo-vet:
    name: Vet Rust dependencies
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Install cargo-vet
        uses: actions-rs/cargo@v1
        with:
          command: install
          args: cargo-vet

      - name: Run cargo vet --locked
        uses: actions-rs/cargo@v1
        with:
          command: vet
          args: --locked
